language: go
go:  
   - "1.8"
   - "1.9"
   - "1.10"
   - "1.11"
before_script: 
    - export GOPATH="$HOME/gopath"
    - go get -d -v
    - make prepare
    - "export LD_LIBRARY_PATH=$PWD/libgit2/install/lib"
    - "export PKG_CONFIG_PATH=$PWD/libgit2/install/lib/pkgconfig"
script: 
   - make test
