language: go
go: 
   - 1.0
   - 1.1 
   - 1.2 
before_script: 
    - make prepare
    - "export LD_LIBRARY_PATH=$PWD/libgit2/install/lib"
    - "export PKG_CONFIG_PATH=$PWD/libgit2/install/lib/pkgconfig"
    - go get
script: 
   - make test
